// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Bank      string
	Number    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Transaction struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Date      time.Time
	Credit    bool
	Amount    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
